apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: udb-ingress
  namespace: udb
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - udb.example.com
      secretName: udb-tls
  rules:
    - host: udb.example.com
      http:
        paths:
          - path: /graphql
            pathType: Prefix
            backend:
              service:
                name: nestjs-graphql
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3030
